// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package persistence

import (
	"time"
)

type Task struct {
	ID        int64     `json:"id"`
	Type      int32     `json:"type"`
	Value     int32     `json:"value"`
	State     string    `json:"state"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
