// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package persistence

import (
	"context"
)

type Querier interface {
	CountTasksByState(ctx context.Context, state string) (int64, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	GetTask(ctx context.Context, id int64) (Task, error)
	ListPendingTasks(ctx context.Context, limit int32) ([]Task, error)
	SumProcessedValues(ctx context.Context) (int64, error)
	UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) error
}

var _ Querier = (*Queries)(nil)
