// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tasks.sql

package persistence

import (
	"context"
)

const countTasksByState = `-- name: CountTasksByState :one
SELECT COUNT(*) FROM tasks WHERE state = $1
`

func (q *Queries) CountTasksByState(ctx context.Context, state string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTasksByState, state)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (type, value, state)
VALUES ($1, $2, 'received')
RETURNING id, type, value, state, created_at, updated_at
`

type CreateTaskParams struct {
	Type  int32 `json:"type"`
	Value int32 `json:"value"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, arg.Type, arg.Value)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Value,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, type, value, state, created_at, updated_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Value,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingTasks = `-- name: ListPendingTasks :many
SELECT id, type, value, state, created_at, updated_at
FROM tasks
WHERE state = 'received'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingTasks(ctx context.Context, limit int32) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listPendingTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Value,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumProcessedValues = `-- name: SumProcessedValues :one
SELECT COALESCE(SUM(value), 0)::bigint FROM tasks WHERE state = 'done'
`

func (q *Queries) SumProcessedValues(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumProcessedValues)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const sumProcessedValuesByType = `-- name: SumProcessedValuesByType :one
SELECT COALESCE(SUM(value), 0)::bigint FROM tasks WHERE state = 'done' AND type = $1
`

func (q *Queries) SumProcessedValuesByType(ctx context.Context, type_ int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumProcessedValuesByType, type_)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateTaskState = `-- name: UpdateTaskState :exec
UPDATE tasks
SET state = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateTaskStateParams struct {
	ID    int64  `json:"id"`
	State string `json:"state"`
}

func (q *Queries) UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskState, arg.ID, arg.State)
	return err
}
